Da respondent
hmcts/prl-citizen-frontend pull request #1165
Opened 2023-10-19 15:49 UTC by sealDebolina

**Before creating a pull request make sure that:**
refactoring DA respondent tasklist to common tasklist

### JIRA link (if applicable) ###

### Change description ###

https://tools.hmcts.net/jira/browse/PRL-4430

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2023-10-23 11:51 UTC, vivek-sekhar requested changes

2023-10-23 11:51 UTC, vivek-sekhar commented on src/main/steps/prl-cases/dashboard/tabView.ts
> +    url = applyParms(`${FETCH_CASE_DETAILS}`, { caseId: caseNumber });
refactor this as discussed

2023-10-23 11:51 UTC, vivek-sekhar commented on src/main/routes.ts
> +    app.get(`${APPLICANT_TASK_LIST_URL}/:caseId`, errorHandler(new CaseDetailsGetController().get));
Revisit this.  Not required.

2023-10-23 11:51 UTC, vivek-sekhar commented on src/main/routes.ts
> +    app.get(RESPONDENT_TASK_LIST_URL, errorHandler(new CaseDetailsGetController().load));
Revisit this.  Not required.

2023-10-24 11:18 UTC, sealDebolina commented on src/main/routes.ts
> +    app.get(RESPONDENT_TASK_LIST_URL, errorHandler(new CaseDetailsGetController().load));
will be taken care in different ticket

2023-10-24 11:18 UTC, sealDebolina commented on src/main/steps/prl-cases/dashboard/tabView.ts
> +    url = applyParms(`${FETCH_CASE_DETAILS}`, { caseId: caseNumber });
done

2023-10-24 15:35 UTC, vivek-sekhar approved these changes
Need to address below items in the next refactoring task,
1. Revisit APPLICANT_TASK_LIST_URL, RESPONDENT_TASK_LIST_URL & ${RESPONDENT_TASK_LIST_URL}/:caseId in routes
2. Revisit src/main/steps/respondent/task-list/index.ts.
3. Revisit src/main/steps/applicant/task-list/index.ts.

2023-10-25 11:12 UTC, AlokDatta approved these changes

2023-11-20 13:55 UTC, merged