Sonarqube code refactor
hmcts/prl-citizen-frontend pull request #1299
Opened 2024-03-01 17:01 UTC by priyankahmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the enable_keep_helm label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2024-03-01 18:17 UTC, sealDebolina requested changes

2024-03-01 18:17 UTC, sealDebolina commented on src/main/steps/tasklistresponse/proceedings/proceedingUtils.ts
> +  const Mapper = getCaseDetailMapper(keys);
refactor if else block

2024-03-01 18:21 UTC, priyankahmcts commented on src/main/app/controller/GetCaseController.ts
> +    originalUrl: string,
This is class, so can't change to arrow function.

2024-03-05 13:13 UTC, priyankahmcts commented on src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
> +   else if(sessionRespondentData[respondent].hasOwnProperty('addressUnknown') && sessionRespondentData[respondent]['addressUnknown'] === YesOrNo.YES){
removed

2024-03-05 13:14 UTC, priyankahmcts commented on src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
> +    pushContactDetails(contactDetails, newRespondentStorage, language, id, 'Email', 'emailAddress', Urls['C100_RESPONDENT_DETAILS_CONTACT_DETAILS']);
refactored

2024-03-05 13:14 UTC, priyankahmcts commented on src/main/steps/tasklistresponse/proceedings/proceedingUtils.ts
> +  const Mapper = getCaseDetailMapper(keys);
removed

2024-03-05 13:23 UTC, priyankahmcts commented on src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
> +    handleC100Case(respondentItems, userCase, taskListItems, respondentItems2);
addressed this comment.

2024-03-05 13:23 UTC, priyankahmcts commented on src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
> +    handleC100Case(respondentItems, userCase, taskListItems, respondentItems2);
addressed this comment.

2024-03-07 11:31 UTC, vivek-sekhar requested changes

2024-03-07 11:31 UTC, vivek-sekhar commented on src/main/app/document/DocumentManagementController.ts
> +    if (originalUrl !== null && originalUrl !== undefined && originalUrl.length > 0) {
Pls use shorthand check

2024-03-07 11:31 UTC, vivek-sekhar commented on src/main/app/document/DocumentManagementController.ts
> +  ) {
Refrain using any for  typing. Also method return type is missing

2024-03-07 11:31 UTC, vivek-sekhar commented on src/main/app/document/DocumentManagementController.ts
> +  private getC7FileNameAndEndPoint(filename: string, endPoint: string, req: AppRequest<Partial<CaseWithId>>) {
return type missing

2024-03-07 11:31 UTC, vivek-sekhar commented on src/main/app/document/DocumentManagementController.ts
> +  private getCAResponseFileNameDocToGetAndUid(
return type missing

2024-03-07 11:31 UTC, vivek-sekhar commented on src/main/app/document/DocumentManagementController.ts
> +  private getFileNameUidAndFieldFlag(
return type missing.

2024-03-07 11:31 UTC, vivek-sekhar commented on src/main/app/document/DocumentManagementController.ts
> +    if (uid.trim() === '') {
use shorthand check

2024-03-07 11:31 UTC, vivek-sekhar commented on src/main/app/document/DocumentManagementController.ts
> +        if (uid !== '') {
use shorthand check

2024-03-07 11:31 UTC, vivek-sekhar commented on src/main/app/document/DocumentManagementController.ts
> +  private searchFileNameByPattern(filename: string, req: AppRequest<Partial<CaseWithId>>, uid: string, fieldFlag: any) {
return type missing

2024-03-07 11:31 UTC, vivek-sekhar commented on src/main/app/document/DocumentManagementController.ts
> +  private respondentDocList(
return type missing

2024-03-07 11:31 UTC, vivek-sekhar reviewed
Has the changes all been tested and working in local dev env comparing AAT flow yet?
Also there are lot other method with no return type as part of your changes. Make sure every method is adressed.

2024-03-12 11:25 UTC, priyankahmcts commented on src/main/app/document/DocumentManagementController.ts
> +    if (originalUrl !== null && originalUrl !== undefined && originalUrl.length > 0) {
Addressed

2024-03-12 11:27 UTC, priyankahmcts commented on src/main/app/document/DocumentManagementController.ts
> +  private getC7FileNameAndEndPoint(filename: string, endPoint: string, req: AppRequest<Partial<CaseWithId>>) {
Addressed

2024-03-12 11:28 UTC, priyankahmcts commented on src/main/app/document/DocumentManagementController.ts
> +  private getCAResponseFileNameDocToGetAndUid(
Addressed

2024-03-12 11:29 UTC, priyankahmcts commented on src/main/app/document/DocumentManagementController.ts
> +  private getFileNameUidAndFieldFlag(
Addressed

2024-03-12 11:29 UTC, priyankahmcts commented on src/main/app/document/DocumentManagementController.ts
> +    if (uid.trim() === '') {
Addressed

2024-03-12 11:29 UTC, priyankahmcts commented on src/main/app/document/DocumentManagementController.ts
> +        if (uid !== '') {
Addressed

2024-03-12 11:30 UTC, priyankahmcts commented on src/main/app/document/DocumentManagementController.ts
> +  private searchFileNameByPattern(filename: string, req: AppRequest<Partial<CaseWithId>>, uid: string, fieldFlag: any) {
Addressed

2024-03-12 11:30 UTC, priyankahmcts commented on src/main/app/document/DocumentManagementController.ts
> +  private respondentDocList(
Addressed

2025-04-27 04:02 UTC, closed without merging