PRL-5346: Notifications for applicant LIP personal service
hmcts/prl-citizen-frontend pull request #1322
Opened 2024-03-08 16:06 UTC by hcarslaw

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PRL-5346

### Change description ###
Adds notifications for CA applicants after they are selected to serve the respondent personally

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-03-11 11:08 UTC, vivek-sekhar requested changes

2024-03-11 11:08 UTC, vivek-sekhar commented on src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
> +        caseData?.state === State.CASE_SERVED &&
Why shd case served be checked when the case is linked?

2024-03-11 11:08 UTC, vivek-sekhar commented on src/main/steps/common/task-list/components/notification-banner/index.ts
> +            ? section?.links
Why optional when you know the section has links already?

2024-03-11 12:15 UTC, hcarslaw commented on src/main/app/case/definition.ts
> +  isApplicationToBeServed?: string
Unable to change to use this as isApplicationToBeServed is a citizenFlag stored in the response and doesn't come directly in the case data

2024-03-11 12:38 UTC, vivek-sekhar requested changes

2024-03-11 12:38 UTC, vivek-sekhar commented on src/main/app/case/definition.ts
> +  isApplicationToBeServed?: string
ok no problem

2024-03-11 12:38 UTC, vivek-sekhar commented on src/main/steps/common/task-list/components/notification-banner/content.ts
> +                  html: '<a href="https://www.gov.uk/government/publications/form-d89-request-for-personal-service-by-a-court-bailiff">https://www.gov.uk/government/publications/form-d89-request-for-
Why html is required. Please use text property rather

2024-03-11 14:17 UTC, vivek-sekhar approved these changes

2024-03-26 16:08 UTC, AlokDatta approved these changes

2024-03-26 16:29 UTC, merged