PRL-5275: Suppress new document notification for CA cases
hmcts/prl-citizen-frontend pull request #1366
Opened 2024-03-22 09:56 UTC by hcarslaw

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PRL-5275

### Change description ###
This suppresses the dashboard notification after documents have been uploaded and reviewed for CA applicant and respondent cases.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-03-23 17:02 UTC, vivek-sekhar approved these changes

2024-03-26 10:13 UTC, vivek-sekhar requested changes
Please remove all the references / functions relating to notification

2024-03-27 11:15 UTC, vivek-sekhar requested changes

2024-03-27 11:15 UTC, vivek-sekhar commented on src/main/app/document/DocumentManagementController.ts
>        const caseDetailsFromCos = await client.retrieveByCaseId(caseData.id, user);
Why this is required?

2024-03-27 12:05 UTC, hcarslaw commented on src/main/app/document/DocumentManagementController.ts
>        const caseDetailsFromCos = await client.retrieveByCaseId(caseData.id, user);
Removed

2024-04-08 09:34 UTC, vivek-sekhar approved these changes

2024-04-08 13:44 UTC, merged