PRL-5550
hmcts/prl-citizen-frontend pull request #1407
Opened 2024-04-17 19:34 UTC by sealDebolina

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the enable_keep_helm label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-04-18 13:26 UTC, vivek-sekhar requested changes

2024-04-18 13:26 UTC, vivek-sekhar commented on src/main/steps/c100-rebuild/miam/child-protection/template.njk
> +<h1 class="govuk-heading-m govuk-!-margin-bottom-3">{{subTitle}}</h1>
Not right to have multiple h1 in a page

2024-04-18 13:26 UTC, vivek-sekhar commented on src/main/steps/c100-rebuild/miam/child-protection/content.ts
>            divider: true,
is the "Or" text showing as per design?

2024-04-22 09:12 UTC, sealDebolina commented on src/main/steps/c100-rebuild/miam/child-protection/content.ts
>            divider: true,
yes

2024-04-22 09:23 UTC, sealDebolina commented on src/main/steps/c100-rebuild/miam/child-protection/template.njk
> +<h1 class="govuk-heading-m govuk-!-margin-bottom-3">{{subTitle}}</h1>
addressed

2024-04-22 09:25 UTC, vivek-sekhar approved these changes

2024-05-07 09:31 UTC, merged