PRL-5516 Before got to Court screen changes
hmcts/prl-citizen-frontend pull request #1412
Opened 2024-04-23 11:15 UTC by hmcts-shajahan

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PRL-5516

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-04-24 08:38 UTC, vivek-sekhar requested changes

2024-04-24 08:38 UTC, vivek-sekhar commented on config/development.yaml
>      url: 'https://api.os.uk/search/places/v1'
can you pls revert dev.yaml

2024-04-24 08:42 UTC, hmcts-shajahan commented on config/development.yaml
>      url: 'https://api.os.uk/search/places/v1'
Reverted.

2024-04-24 09:15 UTC, vivek-sekhar approved these changes

2024-05-01 14:40 UTC, AlokDatta approved these changes

2024-05-01 14:40 UTC, merged