PRL-5661: Routes clean up
hmcts/prl-citizen-frontend pull request #1421
Opened 2024-04-30 14:34 UTC by hcarslaw

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PRL-5661

### Change description ###
Cleans up the routes file

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-04-30 16:12 UTC, vivek-sekhar requested changes

2024-04-30 16:12 UTC, vivek-sekhar commented on src/main/steps/testing-support/get.ts
> -import { GetController } from '../../app/controller/GetController';
chk all testing support files that are deleted with @sealDebolina

2024-04-30 17:19 UTC, hcarslaw commented on src/main/steps/c100-rebuild/start/getController.ts
> +export default class C100StartGetController extends GetController {
Changed to use post controller

2024-04-30 17:19 UTC, hcarslaw commented on src/main/app/controller/PostController.ts
>    private async saveAndContinue(req: AppRequest<T>, res: Response, form: Form, formData: Partial<Case>): Promise<void> {
removed

2024-04-30 18:20 UTC, vivek-sekhar commented on src/main/app/controller/RespondentSubmitResponseController.ts
>    public async getDraftDocument(req: AppRequest, res: Response): Promise<void> {
You can use download doc CC for downloading and create the doc in the controller

2024-05-01 12:57 UTC, vivek-sekhar requested changes

2024-05-01 13:42 UTC, vivek-sekhar approved these changes

2024-05-02 10:35 UTC, merged