PRL-5752: Cafcass - Child lives with changes
hmcts/prl-citizen-frontend pull request #1456
Opened 2024-05-22 10:41 UTC by hcarslaw

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PRL-5752

### Change description ###
Adds a new screen to select who the child mainly lives with and updates the content of the existing child lives with screen.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-05-23 13:05 UTC, vivek-sekhar requested changes

2024-05-23 13:05 UTC, vivek-sekhar commented on src/main/steps/c100-rebuild/child-details/live-with/mainly-live-with/content.ts
> +const en = () => ({
remove fn

2024-05-23 13:05 UTC, vivek-sekhar commented on src/main/steps/c100-rebuild/child-details/live-with/mainly-live-with/content.ts
> +  const people = getPeople(userCase);
no need of variable

2024-05-23 14:42 UTC, vivek-sekhar approved these changes

2024-07-25 14:12 UTC, shashisk97 approved these changes

2024-07-25 14:12 UTC, merged