crnf3 DA cases
hmcts/prl-citizen-frontend pull request #1492
Opened 2024-06-26 10:08 UTC by sealDebolina

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the enable_keep_helm label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-07-23 14:52 UTC, vivek-sekhar requested changes

2024-07-23 14:52 UTC, vivek-sekhar commented on src/main/steps/common/task-list/components/notification-banner/utils.ts
> +export const findMultipleRespondent=(caseData: CaseWithId, commonContent: Record<string, string>)=> {
change to getBannerContentForRespondent

2024-07-24 09:52 UTC, sealDebolina commented on src/main/steps/common/task-list/components/notification-banner/utils.ts
> +export const findMultipleRespondent=(caseData: CaseWithId, commonContent: Record<string, string>)=> {
done

2024-07-26 09:56 UTC, vivek-sekhar approved these changes

2024-07-26 09:56 UTC, vivek-sekhar commented on src/main/steps/common/task-list/components/notification-banner/utils.ts
> +export const getBannerContentForRespondent = (caseData: CaseWithId, commonContent: Record<string, string>) => {
function return type is missing

2024-07-29 12:28 UTC, merged