PRL-5938
hmcts/prl-citizen-frontend pull request #1498
Opened 2024-06-27 17:25 UTC by sealDebolina

### JIRA link (if applicable) ###
PRL-5938

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-07-23 14:41 UTC, vivek-sekhar requested changes

2024-07-23 14:41 UTC, vivek-sekhar commented on src/main/steps/common/documents/download/DownloadDocumentController.ts
> +        documentReference = caseData.respondentDocuments?.find(
Add optional param for respondentDocuments

2024-07-23 14:41 UTC, vivek-sekhar commented on src/main/steps/common/documents/view/all-documents/template.njk
>      </fieldset>
rename the folder to all-categories

2024-07-23 14:41 UTC, vivek-sekhar commented on src/main/steps/common/documents/view/doc/content.ts
> +  let docId;
write a method and name it as getDocumentsMeta which will return documentSectionId & documents

2024-07-23 14:41 UTC, vivek-sekhar commented on src/main/steps/common/documents/view/utils.ts
> +        serveDate: dayjs(_.first(caseData.citizenApplicationPacks!)!.uploadedDate)
check if citizenApplicationPacks is an array and then access the 1st element

2024-07-23 14:41 UTC, vivek-sekhar commented on src/main/steps/common/documents/view/utils.ts
> +          servedDate: dayjs(soaPack.uploadedDate).locale(language).format('DD MMM YYYY'),
same here

2024-07-23 14:41 UTC, vivek-sekhar commented on src/main/steps/common/documents/view/utils.ts
> +          ? (dayjs(_.first(caseData.citizenOrders!)!.madeDate).locale(language).format('DD MMM YYYY') as string)
removed unnecessary mandatory not null check

2024-07-23 14:41 UTC, vivek-sekhar commented on src/main/steps/common/documents/view/utils.ts
> +  const documentId = document.document_url.substring(document.document_url.lastIndexOf('/') + 1);
return the order documents

2024-07-23 14:41 UTC, vivek-sekhar commented on src/main/steps/common/documents/view/utils.ts
> +    if (document) {
chek order.document directly and pass order.document directly

2024-07-23 14:41 UTC, vivek-sekhar commented on src/main/steps/common/documents/view/utils.ts
> +      type = 'applicant';
create enum called DocumentPartyType

2024-07-23 14:41 UTC, vivek-sekhar commented on src/main/steps/common/documents/view/utils.ts
> +      const documentId = generateDocumentID(doc);
don't declare unnecessary variable

2024-10-11 18:31 UTC, vivek-sekhar approved these changes

2024-10-13 10:38 UTC, shashisk97 approved these changes

2024-10-13 10:38 UTC, channa-patil approved these changes

2024-10-13 10:38 UTC, merged