welsh and new link
hmcts/prl-citizen-frontend pull request #1572
Opened 2024-07-22 11:41 UTC by sealDebolina

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the enable_keep_helm label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-07-30 16:02 UTC, vivek-sekhar requested changes

2024-07-30 16:02 UTC, vivek-sekhar commented on src/main/steps/common/task-list/components/tasklist/utils.ts
>  export const getCheckAllegationOfHarmStatus = (caseData): StateTags => {
pass lang param and use the same method for both

2024-07-30 16:02 UTC, vivek-sekhar commented on src/main/steps/common/task-list/components/tasklist/utils.ts
> +export const getCheckAllegationOfHarmStatusWelsh = (caseData): StateTags => {
get rid of it

2024-07-30 16:02 UTC, vivek-sekhar commented on src/main/steps/common/task-list/components/tasklist/utils.ts
>    return _.get(caseData, 'finalDocument.document_binary_url') ? StateTags.READY_TO_VIEW : StateTags.NOT_AVAILABLE_YET;
use same method for both lang

2024-07-30 16:02 UTC, vivek-sekhar commented on src/main/steps/common/task-list/components/tasklist/utils.ts
> +};
get rid of this

2024-07-30 16:02 UTC, vivek-sekhar commented on src/main/steps/common/task-list/components/tasklist/utils.ts
> +export const isRespondentSubmitedResponse = (caseData: Partial<CaseWithId>) => {
Not required

2024-07-31 17:38 UTC, vivek-sekhar requested changes

2024-07-31 17:38 UTC, vivek-sekhar commented on src/main/steps/common/documents/download/DownloadDocumentController.ts
> +              doc.documentLanguage === 'en'
check against lang. no need of if else

2024-07-31 17:38 UTC, vivek-sekhar commented on src/main/steps/common/documents/download/DownloadDocumentController.ts
> +        if (language === 'en') {
use ternary

2024-07-31 17:38 UTC, vivek-sekhar commented on src/main/steps/common/documents/download/DownloadDocumentController.ts
> +        if (language === 'en') {
use ternary

2024-07-31 17:38 UTC, vivek-sekhar commented on src/main/steps/common/documents/download/DownloadDocumentController.ts
> +        if (language === 'en') {
use ternary

2024-07-31 17:38 UTC, vivek-sekhar commented on src/main/steps/common/documents/download/DownloadDocumentController.ts
> +        if (language === 'en') {
check against lang. no need of if else

2024-07-31 17:38 UTC, vivek-sekhar commented on src/main/steps/common/documents/download/DownloadDocumentController.ts
> +          documentReference = caseData?.respondentDocuments?.find(
check against lang. no need of if else

2024-07-31 17:38 UTC, vivek-sekhar commented on src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
> +            language: 'cy',
use contant for lang

2024-07-31 17:38 UTC, vivek-sekhar commented on src/main/steps/common/task-list/components/tasklist/utils.ts
> +  return _.get(caseData, lang === 'en' ? 'finalDocument.document_binary_url' : 'finalWelshDocument.document_binary_url')
use constant for lang

2024-07-31 17:43 UTC, sealDebolina commented on src/main/steps/common/documents/download/DownloadDocumentController.ts
> +        if (language === 'en') {
nested ternary oparator will create sonar issue

2024-07-31 17:43 UTC, sealDebolina commented on src/main/steps/common/documents/download/DownloadDocumentController.ts
> +        if (language === 'en') {
nested ternary oparator will create sonar issue

2024-07-31 17:43 UTC, sealDebolina commented on src/main/steps/common/documents/download/DownloadDocumentController.ts
> +        if (language === 'en') {
nested ternary oparator will create sonar issue

2024-07-31 18:26 UTC, vivek-sekhar approved these changes

2024-07-31 18:30 UTC, merged