6267-6268
hmcts/prl-citizen-frontend pull request #1665
Opened 2024-09-16 15:38 UTC by sealDebolina

…larificaton_on13thSept

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the enable_keep_helm label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-09-18 12:35 UTC, vivek-sekhar requested changes

2024-09-18 12:35 UTC, vivek-sekhar commented on src/main/steps/c100-rebuild/applicant/add-applicants/content.test.ts
> +  title: 'Enter your name  ',
remove space

2024-09-18 12:35 UTC, vivek-sekhar commented on src/main/steps/c100-rebuild/applicant/confidentiality/details-know/content.ts
> +  title: 'Do the other people named in this application (the respondents) know any of your contact details?    ',
remove space

2024-09-18 12:35 UTC, vivek-sekhar commented on src/main/steps/c100-rebuild/hearing-urgency/urgent-details/template.njk
> +<h2 class="govuk-heading-m">{{ reasonForUrgentHearing }}</h1>
wrong closing tag

2024-09-18 12:35 UTC, vivek-sekhar commented on src/main/steps/c100-rebuild/help-with-fees/fees-applied/content.ts
> +                `<h3 class="govuk-heading-m">${l.hwfReferenceNumberLabel}</h3>${l.hwfReferenceNumberBody}`,
check if space required or not.

2024-09-18 12:35 UTC, vivek-sekhar commented on src/main/steps/common/safety-concerns/child/template.njk
> +<h2 class="govuk-heading-m">{{ support }}</h1>
wrong closing tag

2024-09-18 12:35 UTC, vivek-sekhar commented on src/main/steps/common/safety-concerns/no-feedback/template.njk
> +<h2 class="govuk-heading-m">{{subHeading}}</h1>
wrong closing tag

2024-09-18 12:35 UTC, vivek-sekhar commented on src/main/steps/common/safety-concerns/yourself/template.njk
> + <h2 class="govuk-heading-m">{{ support }}</h1>
wrong closing tag

2024-09-18 12:35 UTC, vivek-sekhar commented on src/main/steps/common/statement-of-service/review/template.njk
> +  <h2 class="govuk-heading-m">{{ statementOfTruthHeading }}</h1>
wrong closing tag

2024-09-18 12:35 UTC, vivek-sekhar commented on src/main/steps/common/yourhearings/hearings/template.njk
> +    <h2 class="govuk-heading-m">{{ nextHearingHeading }}</h1>
wrong closing tag

2024-09-18 12:35 UTC, vivek-sekhar commented on src/main/steps/complete-your-application-guidance/template.njk
> +  <h2 class="govuk-heading-m">{{helpPayingCourtFeesSubHeading}}</h1>
wrong closing tag

2024-09-19 12:00 UTC, sealDebolina commented on src/main/steps/c100-rebuild/help-with-fees/fees-applied/content.ts
> +                `<h3 class="govuk-heading-m">${l.hwfReferenceNumberLabel}</h3>${l.hwfReferenceNumberBody}`,
not needed

2024-09-23 10:45 UTC, vivek-sekhar requested changes

2024-09-23 10:45 UTC, vivek-sekhar commented on src/main/steps/application-within-proceedings/guidance/template.njk
> +  <h2 class="govuk-heading-m">{{helpWithFees.title}}</h1>
wrong closing tag

2024-09-23 11:24 UTC, vivek-sekhar approved these changes

2024-09-24 08:11 UTC, merged