feat(PRLC100-126):page for child concern about
hmcts/prl-citizen-frontend pull request #340
Opened 2022-09-26 16:39 UTC by SangeethaPonnusamy

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-09-27 16:28 UTC, channa-patil approved these changes
Looks good to me

2022-09-27 16:56 UTC, channa-patil requested changes

2022-09-28 09:33 UTC, SangeethaPonnusamy commented on src/main/steps/c100-rebuild/safety-concerns/child/concerns-about/content.ts
> +    concernAboutChild: {
@channa-patil - Made the changes as per your request

2022-09-28 11:04 UTC, channa-patil approved these changes

2022-09-28 15:48 UTC, yogendraU approved these changes

2022-09-28 15:49 UTC, merged