feature/c100-rebuild-PRLC100-150
hmcts/prl-citizen-frontend pull request #413
Opened 2022-10-11 18:24 UTC by monalisasarkar1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PRLC100-150

### Change description ###
C1A - Contact between children and other people in the application

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-10-13 09:22 UTC, yogendraU requested changes

2022-10-13 09:41 UTC, monalisasarkar1 commented on src/main/steps/urls.ts
> +export const C100_C1A: PageLink = `${C100_URL}/c1A`;
done

2022-10-13 09:48 UTC, yogendraU requested changes

2022-10-13 09:48 UTC, yogendraU commented on src/main/steps/c100-rebuild/safety-concerns/orders-required/content.ts
> +      section: l => l.section,
is this needed? labelsize and section?

2022-10-13 09:48 UTC, yogendraU commented on src/main/steps/c100-rebuild/safety-concerns/orders-required/content.ts
> +      labelSize: 'm',
same as above comment.

2022-10-13 10:08 UTC, monalisasarkar1 commented on src/main/steps/c100-rebuild/safety-concerns/orders-required/content.ts
> +      section: l => l.section,
yes

2022-10-13 10:08 UTC, monalisasarkar1 commented on src/main/steps/c100-rebuild/safety-concerns/orders-required/content.ts
> +      labelSize: 'm',
yes

2022-10-13 10:59 UTC, yogendraU approved these changes

2022-10-13 11:41 UTC, yogendraU requested changes

2022-10-13 11:41 UTC, yogendraU commented on src/main/app/case/case.ts
> +  c1A_supervisionAgreementDetails?: string;
@monalisasarkar1 , as discussed in today's call, please remove them since i believe there is no conditional routing/mapping for these fields

2022-10-25 22:06 UTC, yogendraU approved these changes

2022-10-25 22:07 UTC, merged