add 'Which children are you concerned about?' checkboxes
hmcts/prl-citizen-frontend pull request #482
Opened 2022-10-25 14:42 UTC by giorgi-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PRLC100-144

### Change description ###
- Added `Which children are you concerned about?(optional)` checkboxes on the page
- Children are dynamically rendered out depending on the number of children filled in on **child-details/add-children** URL

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-10-25 14:47 UTC, giorgi-hmcts commented
When `All of the children in the application` checkbox is ticked and submitted, the userCase receives the data about all children in this format: 
<img width="1620" alt="UserCase when  All of the children in the application  is ticked" src="https://user-images.githubusercontent.com/114390763/197805639-86942ff2-d412-4d95-8744-1fa95411d41c.png">
<br>
Whereas, when children are ticked independently (without ticking the `All of the children in the application` box) the userCase receives the data in a nicely organised way:
<img width="884" alt="userCase when two separate children are ticked" src="https://user-images.githubusercontent.com/114390763/197806043-56542eeb-9686-4516-841e-fca8f1d33b0d.png">

2022-10-25 22:44 UTC, channa-patil requested changes
@giorgi-hmcts Overall look good, data is saved in session.
But checkbox selections are not retained or not loaded from session when we refresh the page.

2022-10-26 15:16 UTC, giorgi-hmcts commented
Checkbox selections are now retained and loaded from userCase session when the page is refreshed or visited back

2022-10-27 09:59 UTC, channa-patil approved these changes

2022-10-27 09:59 UTC, yogendraU approved these changes

2022-10-27 09:59 UTC, merged