add respondent address lookup, manual and select screens feature
hmcts/prl-citizen-frontend pull request #522
Opened 2022-11-05 10:06 UTC by giorgi-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PRLC100-35

### Change description ###
- Added address/lookup screen
- Added address/manual screen
- Added address/select screen
- address postControllers now use URL params 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-11-07 16:51 UTC, giorgi-hmcts commented
There's an issue with `emailAddress` and `telephoneNumber` not being saved in the userCase from the respondent `contact-details` page.

2022-11-08 11:13 UTC, channa-patil requested changes

2022-11-08 11:13 UTC, channa-patil commented on src/main/steps/c100-rebuild/respondent-details/address/lookup/content.ts
> +  const respondentData = content.userCase?.resp_Respondents!.find(
Can we please use common util method getRespndentDetails

2022-11-08 11:13 UTC, channa-patil commented on src/main/steps/c100-rebuild/respondent-details/address/manual/ManualAddressPostController.ts
> +    respondent!.address!.PostCode = req.body['addressPostcode'] as string;
We can use spread operator here I think to reduce these manual assignment.
@vivek-sekhar Can you please add your input ?

2022-11-08 11:13 UTC, channa-patil commented on src/main/steps/c100-rebuild/respondent-details/address/manual/ManualAddressPostController.ts
> +  private getRespondentDetails = (
This is not required, we can use common util getRespndentDetails method please

2022-11-08 11:13 UTC, channa-patil commented on src/main/steps/c100-rebuild/respondent-details/address/manual/content.ts
> +  const respondentData = content.userCase?.resp_Respondents!.find(
Please use common util getRespndentDetails method

2022-11-08 11:13 UTC, channa-patil commented on src/main/steps/c100-rebuild/respondent-details/address/select/SelectAddressPostController.ts
> +        (respondent!.address!.PostCode = selectedAddress.postcode as string),
Same as above comment. We can use spread operator I think

2022-11-08 11:13 UTC, channa-patil commented on src/main/steps/c100-rebuild/respondent-details/address/select/SelectAddressPostController.ts
> +  private getRespondentDetails = (
Can we please use common util getRespndentDetails method

2022-11-08 11:13 UTC, channa-patil commented on src/main/steps/c100-rebuild/respondent-details/address/select/content.ts
> +  const respondentData = content.userCase?.resp_Respondents!.find(
Let's use util getRespndentDetails method please

2022-11-08 11:38 UTC, channa-patil approved these changes
TODO: Need to take care of these comments later in the base branch once all people section changes merged.

2022-11-08 11:39 UTC, merged

2022-11-08 11:43 UTC, giorgi-hmcts commented
Sure @channa-patil. 
Noted to take care of these comments once all people changes are merged.