feat(PRLC100-329): Add dashboard for C100 application
hmcts/prl-citizen-frontend pull request #595
Opened 2022-11-21 17:28 UTC by vivek-sekhar

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-11-21 19:11 UTC, yogendraU requested changes

2022-11-21 19:12 UTC, vivek-sekhar commented on src/main/steps/prl-cases/dashboard/content.ts
> +    yourCAapplication: 'C100 applications where you are an applicant',
All these were present as part of the dashboard code in PR 404

2022-11-21 23:12 UTC, yogendraU approved these changes

2022-11-22 01:10 UTC, yogendraU requested changes

2022-11-22 01:10 UTC, yogendraU commented on src/main/steps/c100-rebuild/applicant/navigationController.ts
> +      case C100_APPLICANT_ADD_APPLICANTS_CONFIDENTIALITY_FEEDBACK:
Hi @vivek-sekhar , this is causing the issue in applicant flow

2022-11-22 12:25 UTC, channa-patil approved these changes

2022-11-22 12:25 UTC, yogendraU approved these changes

2022-11-22 12:25 UTC, merged