Ithc text box validation
hmcts/prl-citizen-frontend pull request #719
Opened 2022-12-23 12:51 UTC by SangeethaPonnusamy

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-01-04 12:27 UTC, AlokDatta commented on src/main/steps/common/confirm-contact-details/contactdetails/content.ts
> +    },
reference for UCD

2023-01-05 12:13 UTC, vivek-sekhar requested changes

2023-01-05 12:13 UTC, vivek-sekhar commented on src/main/steps/c100-rebuild/applicant/add-applicants/content.test.ts
> +        'Rydych wedi defnyddio nod annillys, er enghraifft rhif. Nodwch eich enw gan ddefnyddio llythrennau yn unig. ',
Please remove extra space across all welsh translations.

2023-01-05 12:13 UTC, vivek-sekhar commented on src/main/steps/c100-rebuild/applicant/add-applicants/content.ts
> +          validator: value => isFieldFilledIn(value as string) || isFieldLetters(value),
Typecasting is not required.

2023-01-13 12:01 UTC, merged