COURT ORDER
hmcts/prl-citizen-frontend pull request #847
Opened 2023-03-14 10:36 UTC by sealDebolina

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the keep-helm label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-03-14 11:57 UTC, channa-patil requested changes

2023-03-14 11:57 UTC, channa-patil commented on src/main/steps/applicant/applicantCaseSequence.ts
> +      data.caseTypeOfApplication === 'C100' ? C100_APPLICANT_TASKLIST : APPLICANT_VIEW_ALL_DOCUMENTS,
@sealDebolina Please use constant from definitions for comparison. CaseType.C100

2023-03-15 12:31 UTC, vivek-sekhar approved these changes

2023-03-19 22:36 UTC, channa-patil approved these changes

2023-03-19 22:37 UTC, merged