Citizen testing support
hmcts/prl-citizen-frontend pull request #857
Opened 2023-03-19 22:26 UTC by sealDebolina

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the keep-helm label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-04-04 16:11 UTC, AlokDatta commented on src/main/app/case/C100CaseApi.ts
> +      //console.log(response)
remove commented out code

2023-04-04 16:11 UTC, AlokDatta commented on src/main/app/case/C100CaseApi.ts
> +      //console.log(response)
remove commented out code

2023-04-04 16:11 UTC, AlokDatta commented on src/main/app/testingsupport/TSDraftController.ts
> +  //C100_CASE_NAME,
remove commented out code

2023-04-04 16:11 UTC, AlokDatta commented on src/main/app/testingsupport/TSDraftController.ts
> +  public async createC100Draft(req: AppRequest<AnyObject>, res: Response): Promise<void> {
change this method name to showcase testing support

2023-04-04 16:11 UTC, AlokDatta commented on src/main/app/testingsupport/TSDraftController.ts
> +  public async deleteC100Draft(req: AppRequest<AnyObject>, res: Response): Promise<void> {
change this method name to showcase testing support

2023-04-04 16:11 UTC, AlokDatta commented on src/main/app/testingsupport/TSDraftController.ts
> +        await req.locals.C100Api.updateCase(element, caseData, HOME_URL, C100_CASE_EVENT.DELETE_CASE);
probably a dummy case data will suffice

2023-04-04 16:11 UTC, AlokDatta commented on src/main/routes.ts
> +        app.post(`${CREATE_DRAFT}/deleteC100Draft`, errorHandler(tsDraftController.deleteC100Draft));
get this verified

2023-05-09 14:01 UTC, vivek-sekhar requested changes

2023-05-09 14:01 UTC, vivek-sekhar commented on src/main/routes.ts
> +        const tsDraftController = new TSDraftController(step.form.fields);
Why is this inside the loop?

2023-05-10 17:34 UTC, vivek-sekhar requested changes

2023-05-10 17:34 UTC, vivek-sekhar commented on src/main/routes.ts
> +    const tsDraftController = new TSDraftController();
Instead you can export an instance of the TSDraftController from the class file itself and use it here.

2023-05-12 00:03 UTC, AlokDatta approved these changes

2023-05-12 13:43 UTC, vivek-sekhar approved these changes

2023-05-14 20:11 UTC, merged