cleaning up userCase
hmcts/prl-citizen-frontend pull request #878
Opened 2023-04-12 12:58 UTC by giorgi-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PRL-3426 

### Change description ###
- This PR is cleaning up some of the redundant fields in the userCase
- The cleanup is happening in the mapper/service file of the relevant case

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-04-13 09:36 UTC, vivek-sekhar requested changes

2023-04-13 09:36 UTC, vivek-sekhar commented on yarn-audit-known-issues
> +{"type":"auditAdvisory","data":{"resolution":{"id":1091653,"path":"pcf-start>xml2js","dev":false,"optional":false,"bundled":false},"advisory":{"findings":[{"version":"0.4.23","paths":["pcf-start>xml2
What is added in audit known issues?

2023-04-13 16:05 UTC, giorgi-hmcts commented on yarn-audit-known-issues
> +{"type":"auditAdvisory","data":{"resolution":{"id":1091653,"path":"pcf-start>xml2js","dev":false,"optional":false,"bundled":false},"advisory":{"findings":[{"version":"0.4.23","paths":["pcf-start>xml2
Jenkins build was failing and it asked me to run the command in order to neutralize the vulnerability and make a successful build, I think Debolina had the same issue.

2023-04-14 12:43 UTC, vivek-sekhar approved these changes

2023-04-14 12:43 UTC, vivek-sekhar commented on yarn-audit-known-issues
> +{"type":"auditAdvisory","data":{"resolution":{"id":1091653,"path":"pcf-start>xml2js","dev":false,"optional":false,"bundled":false},"advisory":{"findings":[{"version":"0.4.23","paths":["pcf-start>xml2
This issue needs to be resolved applying necessary patch to the package and not adding it in yarn audit issues file.

2023-04-14 12:48 UTC, merged