response submitted by other respondent
hmcts/prl-citizen-frontend pull request #989
Opened 2023-06-22 13:54 UTC by sealDebolina

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the keep-helm label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-06-26 12:58 UTC, vivek-sekhar requested changes

2023-06-26 12:58 UTC, vivek-sekhar commented on src/main/app/document/DocumentManagementController.ts
> +          for (const document of req.session.userCase.respondentDocsList!) {
you can refactor the two for loops to one by handing conditions inside of the loop

2023-06-28 13:36 UTC, vivek-sekhar approved these changes

2023-06-30 14:49 UTC, AlokDatta approved these changes

2023-07-02 01:59 UTC, merged