Statement of service
hmcts/prl-citizen-frontend pull request #991
Opened 2023-06-27 07:40 UTC by BharadwajSairam

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PRL-3859

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-07-12 10:28 UTC, vivek-sekhar requested changes

2023-07-12 10:28 UTC, vivek-sekhar commented on src/main/app/case/definition.ts
> +export interface test
What is this test interface?

2023-07-12 10:28 UTC, vivek-sekhar commented on src/main/app/controller/PostController.ts
> +    console.log('** req body *** : ' + JSON.stringify(req.body));
remove console statements

2023-07-12 10:28 UTC, vivek-sekhar commented on src/main/app/document/DocumentManagementController.ts
> +    console.log('*** jo jo ***' + JSON.stringify(uploadRequest.partyName));
Remove console statements

2023-07-12 10:28 UTC, vivek-sekhar commented on src/main/steps/applicant/statement-of-service/choose-parties/StatementOfServicePostController.ts
> +        Object.assign(userCase, userData);
why is the request being updated in userCase

2023-07-12 10:28 UTC, vivek-sekhar commented on src/main/steps/applicant/statement-of-service/choose-parties/StatementOfServicePostController.ts
> +        req.session.userCase = await client.updateCase(user, userCase.id, data, CaseEvent.STATEMENT_OF_SERVICE);
updateCase should not be used anymore. Please take a look into other tasklist function postController for reference.

2023-07-12 10:28 UTC, vivek-sekhar commented on src/main/steps/applicant/statement-of-service/choose-parties/content.ts
> +  userCase?.applicants?.forEach(party => {
This constructor is costly. Please use a constructor that takes care of performance.

2023-07-12 10:28 UTC, vivek-sekhar commented on src/main/steps/applicant/statement-of-service/choose-parties/content.ts
> +  userCase?.respondents?.forEach(party => {
This constructor is costly. Please use a constructor that takes care of performance.

2023-07-12 10:28 UTC, vivek-sekhar commented on src/main/steps/common/fileupload/macro.njk
> +<label class="govuk-label govuk-!-font-weight-bold" for="file-upload-1">
add condition to show hint

2023-07-12 10:28 UTC, vivek-sekhar commented on src/main/steps/common/task-list/utils.ts
> +      applicants[0].value.response.citizenFlags?.isApplicationServed === 'Yes' &&
use enum for checking conditions

2025-01-06 11:39 UTC, BharadwajSairam commented
No longer required closing

2025-01-06 11:39 UTC, closed without merging